spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${AWS_DB_DRIVER}
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jwt:
    secret: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
