spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${AWS_DB_DRIVER}
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 5MB # 최대 파일 사이즈
      max-request-size: 5MB # 최대 요청 사이즈

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  cloud:
    aws:
      credentials:
        access_key: ${AWS_ACCESS_KEY}
        secret_key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${BUCKET}
      region:
        static: ${STATIC_REGION}

  jwt:
    secret: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
